### ISSUE TITLE
Show usage

### ISSUE THREAD

**Issue by lukasz-wronski** [aksyonov/mongoose-decorators#1]
Can you show preferred way to access model decorators for generating schema?

**Comment by aksyonov** [comment]
The usage example is shown in readme. You just have to create a class with some methods and apply `model` decorator to it with given schema. Then decorator will convert class into a mongoose model.

**Comment by lukasz-wronski** [comment]
Oh.. decorator will change the class into schema - this is the point I did not understand earlier. Cool. I will test it in next few days and will close this issue when it will work as expected. Thanks for the lib, it's cool that you've created it because it seems to be very useful.

**Comment by aksyonov** [comment]
Closing this issue, if you still have questions please reopen or create new one.
